checking for $DOTFILES too

diff --git a/dotupdate b/dotupdate
--- a/dotupdate
+++ b/dotupdate
@@ -1,6 +1,11 @@
 #! /usr/bin/env sh
 
 
+if [ -z "$DOTFILES" ]; then
+    >&2 echo '"$DOTFILES" is not defined. Aborting.'
+    exit 1
+fi
+
 cd "$DOTFILES/general"
 
 for prog in "$@"; do
