idk

diff --git a/dup b/dup
--- a/dup
+++ b/dup
@@ -1,10 +1,8 @@
 #! /usr/bin/env sh
 
 
-if [ ! -d "$DOTFILES" ]; then
-    >&2 echo '"$DOTFILES" is not defined. Aborting.'
-    exit 1
-fi
+[ ! -d "$DOTFILES" ] &&  >&2 echo '"Aborting.' && exit 1
+
 
 cd "$DOTFILES/general"
 
