fixed bugs in redshiftctl, idup and gui-launch

diff --git a/gui-launch b/gui-launch
--- a/gui-launch
+++ b/gui-launch
@@ -1,29 +1,98 @@
 #! /bin/sh
 
+# vim: foldmethod=marker foldlevel=1
+# shellcheck disable=SC3043
+
+
+desktopfile_lookup_path="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
+desktopfile_lookup_path="$desktopfile_lookup_path:/usr/share/applications"
+
 
 notify_error() {
     notify-send \
-        --expire-time=5000 \
         --icon=dialog-error \
         --urgency=NORMAL \
-        "$1" "$2"
+        "App Launcher" \
+        "$@"
 }
 
 
 notify_launch() {
     notify-send \
-        --expire-time=5000 \
         --icon=preferences-desktop-launch-feedback \
         --urgency=NORMAL \
-        "$1" "$2"
+        "App Launcher" \
+        "$@"
 }
 
 
-if ! which "$1" >/dev/null 2>&1; then
-    notify_error "Error opening '$1'" "No '$1' in <i>\$PATH</i>"
-    exit 1
-else
-    notify_launch "Launching '$1'"
-    exec "$@" &
-fi
+find_filename_in_dirs() {
+    local filename_needle="$1"
+    local dirs_haystack="$2"
+    local separator="${3:-:}"
 
+    printf "%s%s" "$dirs_haystack" "$separator" | while read -rd "$separator" haystack_dir; do
+        if [ -f "$haystack_dir/$filename_needle" ]; then
+            printf "%s/%s" "$haystack_dir" "$filename_needle"
+            return 0 # For some reason this return is ignored by the shell
+        fi
+    done
+    return 1 # This function always returns 1 (??????)
+}
+
+
+launch_desktopfile() {
+    local desktopfile_name="$1"
+    local desktopfile_path="$desktopfile_name"
+
+    if ! [ -f "$desktopfile_path" ]; then
+        desktopfile_path="$(find_filename_in_dirs "$desktopfile_name" "$desktopfile_lookup_path")"
+        >&2 echo "done looking for it"
+    fi
+
+    if [ -z "$desktopfile_path" ]; then
+        notify_error "$(printf "Could not find %q in %q" "$desktopfile_name" "$desktopfile_lookup_path")"
+        return 1
+    fi
+
+    app_name="$(\
+        grep --perl-regexp --only-matching \
+            '(?<=^Name=).+' "$desktopfile_path")"
+    app_icon="$(\
+        grep --perl-regexp --only-matching \
+            '(?<=^Icon=).+' "$desktopfile_path")"
+
+    notify_launch --icon "$app_icon" "Starting $app_name"
+    dex --term="$TERMINAL" "$desktopfile_path"
+}
+
+
+launch_binary() {
+    local app_binary="$1"
+    shift
+
+    if ! command -v "$app_binary" &> /dev/null; then
+        notify_error "$(printf "Could not find %q in \$PATH" "$app_binary")"
+        return 1
+    fi
+
+    notify_launch "$(printf "Starting %q" "$app_binary")"
+    "$app_binary" "$@"
+}
+
+
+main() {
+    if [ $# -lt 1 ]; then
+        >&2 echo "USAGE: $0 <program> [args...]"
+        exit 1
+    fi
+
+    if [ "${1##*.}" = desktop ]; then
+        launch_desktopfile "$@"
+    else
+        launch_binary "$@"
+    fi
+
+}
+
+main "$@"
