removed bug

diff --git a/mvl b/mvl
--- a/mvl
+++ b/mvl
@@ -1,16 +1,61 @@
 #! /bin/sh
 
 
+USAGE="
+SYNOPSYS
+    ${0##*/} [options] [files...]
+
+DESCRIPTION
+    Rename filenames to not contain non-chad characters (diacritics, spaces)
+    If no files are given, use all files present in the current directory.
+    Filenams may be piped into stdin too.
+
+OPTIONS
+    -h, --help
+        Displays this usage information and exits
+
+NOTE
+    If the names of your files conflict with those of the flags, put them
+    after a double dash (--), like this:
+        ${0##*/} -- --help
+    This will rename a file called '--help', instead of activating the
+    '--help' switch.
+"
+
+fatal() {
+    >&2 echo "$@"
+    exit 1
+}
+
+
+args="$(getopt -o "h" -l "help" -n "mvl" -- "$@")" \
+    || fatal "Error parsing arguments!"
+eval set -- "$args"
+
+while true; do
+    case "$1" in
+        '-h'|'--help')
+            echo "$USAGE"
+            exit 0
+            ;;
+        '--')
+            shift
+            break
+            ;;
+    esac
+done
+
+
 src_files="$(mktemp mvl.XXXXXXXXXX --tmpdir)"
 
-if [ $# -gt 0 ]; then
-    if [ "$1" = '-' ]; then
-        cat > "$src_files"
-    else
-        printf '%s\n' "$@" > "$src_files"
-    fi
+if ! [ -t 0 ]; then
+    cat > "$src_files"
 else
-    ls | sed 's|/$||' > "$src_files"
+    if [ $# -gt 0 ]; then
+        printf '%s\n' "$@" > "$src_files"
+    else
+        ls | sed 's|/$||' > "$src_files"
+    fi
 fi
 
 
@@ -30,7 +75,7 @@ while read -r src <&3 && read -r dst <&4; do
     if [ -e "$dst" ]; then
         >&2 echo "DST file '$dst' already exists. Skipping..."
     else
-        mv -vi "$src" "$dst"
+        </dev/tty mv -vi "$src" "$dst"
     fi
 done 3<"$src_files" 4<"$dst_files"
 
